# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven and Erlang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Step 1 - Set up JDK 7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
        
    - name: Step 2 - Set up Erlang
      uses: gleam-lang/setup-erlang@v1.1.2
      with:
        otp-version: 22.3.2
        
    - name: Step 3 - Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging
           
    - name: Step 4  - Set up cache for Maven
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: $ {{ runner.os }}-m2
        
    - name: Step 5 - Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-artifact
        path: staging
        
